### ISSUE TITLE
what argument should i give for aria2c file 

### ISSUE THREAD

**Issue by Paraskalyan001** [mokurin000/fuckingfast-batch-download#1]
is:issue is:open  Hi, mokurin i was using this program to download "https://fitgirl-repacks.site/call-of-duty-wwii/" on windows , i was able to get the links file with the scraper but  i get an error while trying to use extract 
![image](https://github.com/user-attachments/assets/7420d0c4-38ee-41e9-852e-4bd36c0dc32e)

**Comment by mokurin000** [comment]
Did you fill the aria2 output argument? It shouldn't be left empty. You could type cofw.txt for example

You can take a screenshot of the GUI window

**Comment by Paraskalyan001** [comment]
thanks for the guidance , it fetched the direct download links for the rar files and created the codw.txt with the direct download link and corresponding filename . but i think files are not downloaded directly by running the extractor , if there suggestion for fixing that ?
![image](https://github.com/user-attachments/assets/06108600-0a6a-4e10-854e-27a876564a54)
![image](https://github.com/user-attachments/assets/daafe3c1-f335-46d2-b378-596928ab1e66)
![image](https://github.com/user-attachments/assets/98cd8c53-0891-4f01-9414-b9911224c37b)

**Comment by mokurin000** [comment]
> thanks for the guidance , it fetched the direct download links for the rar files and created the codw.txt with the direct download link and corresponding filename . but i think files are not downloaded directly by running the extractor , if there suggestion for fixing that ? ![image](https://private-user-images.githubusercontent.com/88899894/379240298-06108600-0a6a-4e10-854e-27a876564a54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODUyODksIm5iZiI6MTcyOTY4NDk4OSwicGF0aCI6Ii84ODg5OTg5NC8zNzkyNDAyOTgtMDYxMDg2MDAtMGE2YS00ZTEwLTg1NGUtMjdhODc2NTY0YTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDEyMDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZjViOGE4MTFhZDdhYTQ0YzEyNDMxODNiYWZiMWZhNzZkNzA5MjU1NTJlODJiZGE2OWZkY2UwYTIxY2ZlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8Xk93WMM1Qb4_X5eK81fSGfLNVSKTWU_dRWI2dfOZtM) ![image](https://private-user-images.githubusercontent.com/88899894/379240330-daafe3c1-f335-46d2-b378-596928ab1e66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODUyODksIm5iZiI6MTcyOTY4NDk4OSwicGF0aCI6Ii84ODg5OTg5NC8zNzkyNDAzMzAtZGFhZmUzYzEtZjMzNS00NmQyLWIzNzgtNTk2OTI4YWIxZTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDEyMDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMmJhYjc2MDBmM2YxYjc2YWY4YmE4NTc4MzQ4NGZmNTM3ZjA1YmYxNjFlY2IzNWYwYWI5MDAzNGU2ZGU4NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NEFyn6XIEib1cqjt42GVGS3PmDRRUyDIrf2uwORELq8) ![image](https://private-user-images.githubusercontent.com/88899894/379240345-98cd8c53-0891-4f01-9414-b9911224c37b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODUyODksIm5iZiI6MTcyOTY4NDk4OSwicGF0aCI6Ii84ODg5OTg5NC8zNzkyNDAzNDUtOThjZDhjNTMtMDg5MS00ZjAxLTk0MTQtYjk5MTEyMjRjMzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDEyMDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyN2IwNmVjZTQ0NjkwYzNjYzdmODQ2ZGNkOTc3NjUyZTViZjIwN2RjNzEzOTc3ZGU5ZGE0ODZhYWFjNzIzNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IrnLTNSJKWruCWf9ZQJxsxL4cmg18012EG-9SWuKEmM)

This is the expected behaviour. The next step is to run aria2c/Motrix, import the input file, set slice number to one, concurrent job number to about 4

**Comment by mokurin000** [comment]
> thanks for the guidance , it fetched the direct download links for the rar files and created the codw.txt with the direct download link and corresponding filename . but i think files are not downloaded directly by running the extractor , if there suggestion for fixing that ? ![image](https://private-user-images.githubusercontent.com/88899894/379240298-06108600-0a6a-4e10-854e-27a876564a54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODUyODksIm5iZiI6MTcyOTY4NDk4OSwicGF0aCI6Ii84ODg5OTg5NC8zNzkyNDAyOTgtMDYxMDg2MDAtMGE2YS00ZTEwLTg1NGUtMjdhODc2NTY0YTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDEyMDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZjViOGE4MTFhZDdhYTQ0YzEyNDMxODNiYWZiMWZhNzZkNzA5MjU1NTJlODJiZGE2OWZkY2UwYTIxY2ZlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8Xk93WMM1Qb4_X5eK81fSGfLNVSKTWU_dRWI2dfOZtM) ![image](https://private-user-images.githubusercontent.com/88899894/379240330-daafe3c1-f335-46d2-b378-596928ab1e66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODUyODksIm5iZiI6MTcyOTY4NDk4OSwicGF0aCI6Ii84ODg5OTg5NC8zNzkyNDAzMzAtZGFhZmUzYzEtZjMzNS00NmQyLWIzNzgtNTk2OTI4YWIxZTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDEyMDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMmJhYjc2MDBmM2YxYjc2YWY4YmE4NTc4MzQ4NGZmNTM3ZjA1YmYxNjFlY2IzNWYwYWI5MDAzNGU2ZGU4NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NEFyn6XIEib1cqjt42GVGS3PmDRRUyDIrf2uwORELq8) ![image](https://private-user-images.githubusercontent.com/88899894/379240345-98cd8c53-0891-4f01-9414-b9911224c37b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODUyODksIm5iZiI6MTcyOTY4NDk4OSwicGF0aCI6Ii84ODg5OTg5NC8zNzkyNDAzNDUtOThjZDhjNTMtMDg5MS00ZjAxLTk0MTQtYjk5MTEyMjRjMzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDEyMDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyN2IwNmVjZTQ0NjkwYzNjYzdmODQ2ZGNkOTc3NjUyZTViZjIwN2RjNzEzOTc3ZGU5ZGE0ODZhYWFjNzIzNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IrnLTNSJKWruCWf9ZQJxsxL4cmg18012EG-9SWuKEmM)

You can also check my video on Bilibili/Youtube, through it's in Chinese, youtube should provide auto-translation

https://m.youtube.com/watch?v=gympGkzoclY&t=131s
